# Generated by Django 5.0.1 on 2024-02-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='information',
            table='Information',
        ),
    ]
