# Generated by Django 5.0.1 on 2024-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapk', '0002_alter_information_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
